routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CommentController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('post', PostController::class);
Route::resource('dashboard', DashboardController::class);
Route::resource('profile', ProfileController::class);
Route::resource('comment', CommentController::class);

Auth::routes();

Route::get('/', [App\Http\Controllers\PostController::class, 'index'])->name('home');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Comment;
use Illuminate\Database\Eloquent\Category;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Post extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function user(){
        return $this->belongsTo('App\Models\User');
    }

    public function comment(){
        return $this->belongsToMany('App\Models\Comment','comments', 'user_id', 'posts_id');
    }
    public function Category(){
        return $this->hasOne('App\Models\Category');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\post;
use App\Models\comment;
use Auth;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $list = post::all();
        
        return view('post/index', compact('list'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $post = post::find($id);
        //$comments = comment::where('posts_id', $id)->get();
        $comments = comment::where('posts_id', $id)->join('users', 'comments.user_id', '=', 'users.id')->get();
        return view('post/show',compact('post'),compact('comments'));
    
        }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        }
}

resources/views/post/index.blade.php
@extends('adminlte.master')
{{-- @section('background')
<div class="jumbotron jumbotron-fluid" style="background-image: url({{ asset('img/bg.jpg') }});background-size:100%">
    <div class="container" style="color: white">
      <h1>Bootstrap Tutorial</h1>
      <p>Bootstrap is the most popular HTML, CSS...</p>
    </div>
  </div>
@endsection --}}
@section('content')
<div class="container">
  <div class="card card-primary m-3">
      <div class="card-header">
        <h3 class="card-title">Recent discussion and answers</h3>
      </div>
      <!-- /.card-header -->
      @forelse ($list as $key => $item)
              <div class="media border p-3 mb-3">
        <img src="{{ asset('adminlte/dist/img/user2-160x160.jpg') }}" alt="John Doe" class="mr-3 mt-3 rounded-circle" style="width:60px;">
        <div class="media-body">
          <h4><a style="color: black" href="{{ route('post.show',['post'=>$item->id]) }}">{{  $item->judul }}</a> </h4>
          <p>{{  $item->isi }}</p>
          <small><i>Posted on {{  $item->created_at->diffForHumans() }}</i></small>
        </div>
      </div>

              @empty
              <center class="mt-3">No Data</center>
              
          @endforelse
      
        <!-- /.card-body -->
  
        <div class="card-footer">
          
        </div>
    </div>
  </div>

@endsection

resources/views/post/show.blade.php
@extends('adminlte.master')
{{-- @section('background')
<div class="jumbotron jumbotron-fluid" style="background-image: url({{ asset('img/bg.jpg') }});background-size:100%">
    <div class="container" style="color: white">
      <h1>Bootstrap Tutorial</h1>
      <p>Bootstrap is the most popular HTML, CSS...</p>
    </div>
  </div>
@endsection --}}
@section('content')
<div class="container">
  <div class="card card-primary m-3">
      <div class="card-header">
        <h3 class="card-title">Recent discussion and answers</h3>
      </div>
      <!-- /.card-header -->
      <div class="media border p-3 mb-3">
        <img src="{{ asset('adminlte/dist/img/user2-160x160.jpg') }}" alt="John Doe" class="mr-3 mt-3 rounded-circle" style="width:60px;">
        <div class="media-body">
          <h4>{{  $post->judul }} <small><i>Posted on {{  $post->created_at->diffForHumans() }}</i></small></h4>
          <p>{{  $post->isi }}</p>
        </div>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
          <i class="fa fa-plus mr-3" aria-hidden="true"></i>Comment
        </button>
      </div>     
      <!--  Tambah Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form action="/comment" method="POST">
        @csrf
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Comment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <input type="text" class="form-control" name="post_id" id="post_id" value="{{  $post->id }}" hidden>
        </div>
        <div class="form-group">
          <textarea class="form-control" rows="5" name="isi" id="isi"></textarea>
        </div>
        @error('isi')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" value="submit">Submit</button>
      </div>
      </form>
    </div>
  </div>
</div>   
      
        <!-- /.card-body -->
  
        <div class="card-footer">
          
        </div>
    </div>

    @forelse ($comments as $comment)
    <div class="media border p-3 mb-3">
      <img src="{{ asset('adminlte/dist/img/user2-160x160.jpg') }}" alt="John Doe" class="mr-3 mt-3 rounded-circle" style="width:60px;">
      <div class="media-body">
        <h4>{{  $comment->name }} </h4>
        <p>{{  $comment->isi }}</p>
        <small><i>Commented on {{  $post->created_at->diffForHumans() }}</i></small>
      </div>
      @if ($comment->user_id == Auth::user()->id)
      <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#editModal{{ $comment->id }}" data-toggle="tooltip" title="Edit">
        <i class="fa fa-edit" aria-hidden="true"></i>
      </button>
                <form action="/comment/{{ $comment->id }}" method="post">
                  @csrf
                  @method('delete')
                  <input type="text" class="form-control" name="post_id" id="post_id" value="{{  $post->id }}" hidden>
                  <input type="submit" value="Delete" class="btn btn-danger btn-sm ml-2">
                  </form>
      @endif
    </div>

    <!-- Edit Modal -->
    <div class="modal fade" id="editModal{{ $comment->id }}" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <form action="/comment/{{$comment->id}}" method="POST">
            @csrf
            @method('put')
          <div class="modal-header">
            <h5 class="modal-title" id="editModalLabel">Comment</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="form-group">
              <input type="text" class="form-control" name="post_id" id="post_id" value="{{  $post->id }}" hidden>
            </div>
            <div class="form-group">
              <textarea class="form-control" rows="5" name="isi" id="isi" >{{  old('isi',$comment->isi) }}</textarea>
            </div>
            @error('isi')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary" value="submit">Submit</button>
          </div>
          </form>
        </div>
      </div>
    </div> 
    @empty
        
    
    @endforelse


  </div>

@endsection