routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CommentController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('post', PostController::class);
Route::resource('dashboard', DashboardController::class);
Route::resource('profile', ProfileController::class);
Route::resource('comment', CommentController::class);

Auth::routes();

Route::get('/', [App\Http\Controllers\PostController::class, 'index'])->name('home');

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\post;
use App\Models\category;
use Auth;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        //$id =Auth::user()->id;
       //$list = Post::where('user_id', $id)->get();
       $user = Auth::user();
       $list = $user->post;
        return view('dashboard/index', compact('list'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $kategori = category::all();
        return view('dashboard/create', compact('kategori'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $dashboard = new post;

        $request->validate([
            'judul' => 'required',
            'isi' => 'required',
            'categories_id' => 'required',
        ]);
        // $dashboard = post::create([
        //     "judul" => $request['judul'],
        //     "isi" => $request['isi'],
        //     "categories_id" => $request['categories_id'],
        //     "user_id" => Auth::user()->id
        // ]);

        $user = Auth::user();
        //$user->post()->save($dashboard);
        $dashboard = $user->post()->create([
            "judul" => $request['judul'],
            "isi" => $request['isi'],
            "categories_id" => $request['categories_id'],
        ]);

        return redirect('dashboard')->with('toast_success', 'Data Berhasil Ditambahkan');
    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $post = post::find($id);
        return view('dashboard/show',compact('post'));
    
    
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $kategori = category::all();
        $post = post::find($id);
        return view('dashboard/edit',compact('post'), compact('kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->validate([
            'judul' => 'required',
            'isi' => 'required',
            'categories_id' => 'required',
        ]);
        $dashboard = post::where("id",$id)
        ->update([
            "judul" => $request['judul'],
            "isi" => $request['isi'],
            "categories_id" => $request['categories_id'],
            "user_id" => Auth::user()->id
        ]);
        return redirect('dashboard')->with('toast_success', 'Data Berhasil Diubah!');
    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $delete=post::destroy($id);
        return redirect('dashboard')->with('toast_success', 'Data Berhasil Dihapus!');
    
    }
}

resources/views/dashboard/create.blade.php
@extends('adminlte.master')

@section('content')
<div class="container">
<div class="card card-primary m-3">
    <div class="card-header">
      <h3 class="card-title">Add New Discussion</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form action="/dashboard" method="POST">
      @csrf
      <div class="card-body">
        <div class="form-group">
          <label for="judul">Judul :</label>
          <input type="text" class="form-control" name="judul" id="judul" >
        </div>
        @error('judul')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group">
          <label for="categories_id">Kategori :</label>
          <select class="form-control" class="form-control" name="categories_id" id="categories_id" style="width: 100%;" data-select2-id="1" tabindex="-1" aria-hidden="true">
            @foreach ($kategori as $item)
            <option data-select2-id="{{ $item->id }}" value="{{ $item->id }}">{{ $item->name }}</option>
            @endforeach
          </select>
        </div>
        <div class="form-group">
          <label for="isi">Isi :</label>
          <textarea class="form-control" rows="5" name="isi" id="isi"></textarea>
        </div>
        @error('isi')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
      </div>
      <!-- /.card-body -->

      <div class="card-footer">
        <button type="submit" class="btn btn-primary" value="submit">Submit</button>
      </div>
    </form>
  </div>
</div>
@endsection

resources/views/dashboard/edit.blade.php
@extends('adminlte.master')

@section('content')
<div class="container">
<div class="card card-primary m-3">
    <div class="card-header">
      <h3 class="card-title">Add New Discussion</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form action="/dashboard/{{$post->id}}" method="POST">
      @csrf
      @method('PUT')
      <div class="card-body">
        <div class="form-group">
          <label for="judul">Judul :</label>
          <input type="text" class="form-control" name="judul" id="judul" value="{{ old('judul', $post->judul) }}">
        </div>
        @error('judul')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group">
          <label for="categories_id">Kategori :</label>
          <select class="form-control" class="form-control" name="categories_id" id="categories_id" style="width: 100%;" data-select2-id="1" tabindex="-1" aria-hidden="true">
            @foreach ($kategori as $item)
            @if (old('categories_id', $post->categories_id)==$item->id)
            <option data-select2-id="{{ $item->id }}" value="{{ $item->id }}" selected>{{ $item->name }}</option>
            @else
            <option data-select2-id="{{ $item->id }}" value="{{ $item->id }}">{{ $item->name }}</option>
            @endif
            
            @endforeach
          </select>
        </div>
        <div class="form-group">
          <label for="isi">Isi :</label>
          <textarea class="form-control" rows="5" name="isi" id="isi">{{ old('isi', $post->isi) }}</textarea>
        </div>
        @error('isi')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
      </div>
      <!-- /.card-body -->

      <div class="card-footer">
        <button type="submit" class="btn btn-primary" value="submit">Submit</button>
      </div>
    </form>
  </div>
</div>
@endsection

resources/views/dashboard/index.blade.php
@extends('adminlte.master')
{{-- @section('background')
<div class="jumbotron jumbotron-fluid" style="background-image: url({{ asset('img/bg.jpg') }});background-size:100%">
    <div class="container" style="color: white">
      <h1>Bootstrap Tutorial</h1>
      <p>Bootstrap is the most popular HTML, CSS...</p>
    </div>
  </div>
@endsection --}}
@section('content')
<div class="container">
  <a class="btn btn-primary ml-3 mt-3" href="{{ route('dashboard.create') }}"><i class="fa fa-plus mr-3" aria-hidden="true"></i>Add New Discussion</a>
  <div class="card card-primary m-3">
      <div class="card-header">
        <h3 class="card-title">Your discussion</h3>
      </div>
      <!-- /.card-header -->
      @forelse ($list as $key => $item)
              <div class="media border p-3 mb-3">
        <img src="{{ asset('adminlte/dist/img/user2-160x160.jpg') }}" alt="John Doe" class="mr-3 mt-3 rounded-circle" style="width:60px;">
        <div class="media-body">
          <h4>{{  $item->judul }} <small><i>Posted on {{  $item->created_at }}</i></small></h4>
          <p>{{  $item->isi }}</p>
        </div>
        <a class="btn btn-primary btn-sm ml-2" href="/dashboard/{{ $item->id }}/edit" data-toggle="tooltip" title="Edit">
          Edit
        </a>
                  <form action="/dashboard/{{ $item->id }}" method="post">
                    @csrf
                    @method('delete')
                    <input type="submit" value="Delete" class="btn btn-danger btn-sm ml-2">
                    </form>
      </div>

              @empty
              <center class="mt-3">No Data</center>
            
              
          @endforelse
        <!-- /.card-body -->
  
        <div class="card-footer">
          
        </div>
    </div>
  </div>

@endsection